network: # basic MLP layer configuration
  num_networks: 5
  layer_sizes: [50]
optimizer:
  class : Adam
  lr : 0.001
dataset: # for now, just use toy-dataset
  class: 'csv'
  path: "regression_datasets/boston.csv"
  batch_size : 128   
train:
  num_iter : 10000
  print_every : 2500
  weighted : False
logger:
  type: 'wandb'
  project: 'uncertainty-estimation'
  entity: 'kbora'
  name: 'Boston Dataset Non-Weighted'