network: # basic MLP layer configuration
  num_networks: 5
  layer_sizes: [50]
dataset: # for now, just use toy-dataset
  class: 'xls'
  path: "regression_datasets/Concrete_Data.xls"
  batch_size : 128   
train:
  num_iter : 10000
  print_every : 2500
  weighted : True
logger:
  type: 'wandb'
  project: 'uncertainty-estimation'
  entity: 'kbora'
  name: 'Concrete Dataset Weighted'