estimator: # basic MLP layer configuration
  class: 'ensemble'
  model:
    num_networks : 5
    layer_sizes : [100]
  optimizer:
    class : 'Adam'
    lr : 0.01
dataset: # for now, just use toy-dataset
  class: 'xls'
  path: "regression_datasets/year_prediction.csv"
  batch_size : 128   
  cv_split_num: 1
  test_ratio: 0.10
  y_col : [0]
transforms:
  x :
    - class : standardize
  y :
    - class : standardize
train:
  train_type : epoch
  num_iter : 40
  print_every : 5 
  val_every: 10
logger:
  type: 'wandb'
  project: 'uncertainty-estimation'
  entity: 'kbora'
  name: 'Toy Dataset Complex Weighted'